# Generated by Django 5.2.5 on 2025-08-28 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('apelido', models.CharField(blank=True, max_length=60, verbose_name='Apelido')),
                ('cpf', models.CharField(help_text='Apenas números (ex.: 12345678901).', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Informe 11 dígitos, somente números.')], verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{1,14}$', 'Use o formato E.164, ex.: +5511999999999.')], verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Não informado')], max_length=1, verbose_name='Sexo')),
                ('logradouro', models.CharField(blank=True, max_length=120, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=60, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=60, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, help_text='Apenas números (ex.: 69900970).', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe 8 dígitos, somente números.')], verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cpf'], name='core_pessoa_cpf_2292ad_idx'), models.Index(fields=['nome'], name='core_pessoa_nome_124496_idx')],
            },
        ),
    ]
